import Head from 'next/head';
import React from 'react';
import Hero from '../components/Hero';
import Navbar from '../components/Navbar';
import About from '../components/About';
import WhatIDo from '../components/WhatIDo';
import Skill from '../components/Skill';
import Blog from '../components/Blog';
import Contact from '../components/Contact';
import Footer from '../components/Footer';
import { useState } from 'react';


const Home = () => {
  const [isOpen, setIsOpen] = useState(false);

  const toggleSidebar = () => {
    setIsOpen(!isOpen);
  };

  return (
    <div>
      <Head>
        <title>Siraw Tadesse | Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
        <Navbar toggleSidebar={toggleSidebar} />
      </header>
      <main>
        <Hero />
        <About  />
        <WhatIDo />
        <Skill />
        <Blog />
        <Contact />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
};

export default Home;